# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            'OpenNMT'
tagline:          'Open-Source Neural Machine Translation'
description:      'An open-source neural machine translation system.'
url:              http://opennmt.net
baseurl:          http://opennmt.net
google_analytics: UA-89222039-1
author:
  name:           'Yoon Kim and HarvardNLP'
  url:            https://twitter.com/harvardnlp


# Custom vars
version:          0.1

github:
  repo:           https://github.com/opennmt/opennmt
